### ISSUE TITLE
(solved) Windows Driver

### ISSUE THREAD

**Issue by Uefi1** [morrownr/8821cu#15]
Hello for Linux, the driver works great, can you build it for windows and android ?

**Comment by morrownr** [comment]
Hi Uefi1,

Glad you are having success with this driver. Can I build it for Windows? I cannot due to several reasons. I don't have or support any systems that have Windows installed. My history with operating systems on small computers is CP/M, PC-DOS, DR-DOS, OS/2 and Linux. Can I compile it for Android? That would be closer to possible since Android is based on Linux but I do not have the development environment setup and I am close to maxed out on my time available as it is.

Nick
