### ISSUE TITLE
/var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_mp.c:31:5: error: ‘-mgeneral-regs-only’ is incompatible with floating-point argument

### ISSUE THREAD

**Issue by reverendo7zero** [morrownr/8821cu#3]
Hello,
thank you for the very detailed guide.
I have the following output during the headers installation:

CC [M]  /var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_mp.o
/var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_mp.c: In function ‘rtfloor’:
/var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_mp.c:31:5: error: ‘-mgeneral-regs-only’ is incompatible with floating-point argument
 int rtfloor(float x)
     ^~~~~~~
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_mp.o] Error 1
make[1]: *** [Makefile:1732: /var/lib/dkms/rtl8821CU/5.4.1/build] Error 2
make[1]: uscita dalla directory "/usr/src/linux-headers-5.4.79-v8+"
make: *** [Makefile:2214: modules] Error 2

Any idea ?
Cheers.

**Comment by morrownr** [comment]
What OS are you using? 64 bit? Hardware platform?

**Comment by reverendo7zero** [comment]
Hello,
Apologies for the lack of info.

What OS are you using? Raspberry OS
64 bit? Yes, it's the experimental version of the OS, latest release
Hardware platform? Raspberry pi 4

Lodovico Pesenti

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by morrownr** [comment]
Lodivico,

I suspected it was Raspberry Pi OS 64 bit. Some recent discussions regarding RasPi OS 64 bit have been taking place in Issues on my 88x2bu driver. I am not testing the 64 bit version yet but as best we can tell, this is a problem with RasPi OS 64. You might want to report it at the appropriate place for bugs for RasPi 64 bit. I have both a RasPi 3B and 4B and I do test these drivers on them. The problem is a lack of time to test everything. I will test the new 64 bit RasPi OS when it is stable and released for general use. if you have an extra sd card, you might load up and test the 32 bit version with this driver.

**Comment by reverendo7zero** [comment]
Hello,
I suspected the OS version as well, yes.
Will do some tests, but I'm quite confident it will work on the 32bit version.

Thank you for taking the time to deal with this issue of mine: will close the issue.

Cheers and take care !

**Comment by reverendo7zero** [comment]
...
